"""init

Revision ID: 2fd754769a6f
Revises:
Create Date: 2026-04-21 19:19:41.091367

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2fd754769a6f"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("watchlist", "stock_code", existing_type=sa.VARCHAR(length=20), nullable=True)
    op.create_index(op.f("ix_watchlist_id"), "watchlist", ["id"], unique=False)
    op.create_index(op.f("ix_watchlist_stock_code"), "watchlist", ["stock_code"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_watchlist_stock_code"), table_name="watchlist")
    op.drop_index(op.f("ix_watchlist_id"), table_name="watchlist")
    op.alter_column("watchlist", "stock_code", existing_type=sa.VARCHAR(length=20), nullable=False)
    # ### end Alembic commands ###
