"""add_stock_daily_prices_and_indicators

Revision ID: 46ef13493fcc
Revises: 2fd754769a6f
Create Date: 2026-04-21 21:34:20.537879

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "46ef13493fcc"
down_revision: str | Sequence[str] | None = "2fd754769a6f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stock_daily_prices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("stock_code", sa.String(length=20), nullable=False),
        sa.Column("trade_date", sa.DateTime(), nullable=False),
        sa.Column("open", sa.Float(), nullable=True),
        sa.Column("high", sa.Float(), nullable=True),
        sa.Column("low", sa.Float(), nullable=True),
        sa.Column("close", sa.Float(), nullable=True),
        sa.Column("volume", sa.Integer(), nullable=True),
        sa.Column("amount", sa.Float(), nullable=True),
        sa.Column("is_suspended", sa.Integer(), nullable=True),
        sa.Column("adjusted", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_stock_daily_prices_id"), "stock_daily_prices", ["id"], unique=False)
    op.create_index(
        op.f("ix_stock_daily_prices_stock_code"), "stock_daily_prices", ["stock_code"], unique=False
    )
    op.create_table(
        "stock_indicators",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("stock_code", sa.String(length=20), nullable=False),
        sa.Column("trade_date", sa.DateTime(), nullable=False),
        sa.Column("ma5", sa.Float(), nullable=True),
        sa.Column("ma10", sa.Float(), nullable=True),
        sa.Column("ma20", sa.Float(), nullable=True),
        sa.Column("ma60", sa.Float(), nullable=True),
        sa.Column("rsi6", sa.Float(), nullable=True),
        sa.Column("rsi12", sa.Float(), nullable=True),
        sa.Column("rsi24", sa.Float(), nullable=True),
        sa.Column("macd_dif", sa.Float(), nullable=True),
        sa.Column("macd_dea", sa.Float(), nullable=True),
        sa.Column("macd_bar", sa.Float(), nullable=True),
        sa.Column("kdj_k", sa.Float(), nullable=True),
        sa.Column("kdj_d", sa.Float(), nullable=True),
        sa.Column("kdj_j", sa.Float(), nullable=True),
        sa.Column("boll_upper", sa.Float(), nullable=True),
        sa.Column("boll_mid", sa.Float(), nullable=True),
        sa.Column("boll_lower", sa.Float(), nullable=True),
        sa.Column("vol_ma5", sa.Float(), nullable=True),
        sa.Column("vol_ma10", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_stock_indicators_id"), "stock_indicators", ["id"], unique=False)
    op.create_index(
        op.f("ix_stock_indicators_stock_code"), "stock_indicators", ["stock_code"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_stock_indicators_stock_code"), table_name="stock_indicators")
    op.drop_index(op.f("ix_stock_indicators_id"), table_name="stock_indicators")
    op.drop_table("stock_indicators")
    op.drop_index(op.f("ix_stock_daily_prices_stock_code"), table_name="stock_daily_prices")
    op.drop_index(op.f("ix_stock_daily_prices_id"), table_name="stock_daily_prices")
    op.drop_table("stock_daily_prices")
    # ### end Alembic commands ###
