"""add users and user_id columns

Revision ID: 6568642d9a6b
Revises: 001
Create Date: 2026-04-22 10:59:39.365343

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6568642d9a6b"
down_revision: str | Sequence[str] | None = "001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=True),
        sa.Column("email", sa.String(length=100), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.add_column("alerts", sa.Column("user_id", sa.Integer(), nullable=True))
    op.create_index(op.f("ix_alerts_user_id"), "alerts", ["user_id"], unique=False)
    op.add_column("diagnostic_history", sa.Column("user_id", sa.Integer(), nullable=True))
    op.create_index(
        op.f("ix_diagnostic_history_user_id"), "diagnostic_history", ["user_id"], unique=False
    )
    op.add_column("positions", sa.Column("user_id", sa.Integer(), nullable=True))
    op.create_index(op.f("ix_positions_user_id"), "positions", ["user_id"], unique=False)
    op.add_column("strategy_backtests", sa.Column("user_id", sa.Integer(), nullable=True))
    op.create_index(
        op.f("ix_strategy_backtests_user_id"), "strategy_backtests", ["user_id"], unique=False
    )
    op.add_column("transactions", sa.Column("user_id", sa.Integer(), nullable=True))
    op.create_index(op.f("ix_transactions_user_id"), "transactions", ["user_id"], unique=False)
    op.add_column("watchlist", sa.Column("user_id", sa.Integer(), nullable=True))
    op.create_index(op.f("ix_watchlist_user_id"), "watchlist", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_watchlist_user_id"), table_name="watchlist")
    op.drop_column("watchlist", "user_id")
    op.drop_index(op.f("ix_transactions_user_id"), table_name="transactions")
    op.drop_column("transactions", "user_id")
    op.drop_index(op.f("ix_strategy_backtests_user_id"), table_name="strategy_backtests")
    op.drop_column("strategy_backtests", "user_id")
    op.drop_index(op.f("ix_positions_user_id"), table_name="positions")
    op.drop_column("positions", "user_id")
    op.drop_index(op.f("ix_diagnostic_history_user_id"), table_name="diagnostic_history")
    op.drop_column("diagnostic_history", "user_id")
    op.drop_index(op.f("ix_alerts_user_id"), table_name="alerts")
    op.drop_column("alerts", "user_id")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
