"""add screener_templates

Revision ID: 907cfd0caa9f
Revises: 6568642d9a6b
Create Date: 2026-04-22 11:27:57.911361

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "907cfd0caa9f"
down_revision: str | Sequence[str] | None = "6568642d9a6b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "screener_templates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.Column("conditions", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_screener_templates_id"), "screener_templates", ["id"], unique=False)
    op.create_index(
        op.f("ix_screener_templates_user_id"), "screener_templates", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_screener_templates_user_id"), table_name="screener_templates")
    op.drop_index(op.f("ix_screener_templates_id"), table_name="screener_templates")
    op.drop_table("screener_templates")
    # ### end Alembic commands ###
